### ISSUE TITLE
How to deploy this script.

### ISSUE THREAD

**Issue by brown7477** [EyuCoder/chatgpt-clone#5]
Is it possible for you give some instructions on how to deploy this?
I love the demo and want to play with it a little and see if I can add some more functionality too it.
But it is awesome the way it is now.

**Comment by EyuCoder** [comment]
you can deploy the server to render.com and the client to netlify or vencel or any other hosting service that supports react apps

**Comment by uyriq** [comment]
Hi! I'm asking here because I hope this is acceptable. tell me more about firestore-hosting setup, if I understand correctly what is needed:
1. in the server.js file
```  
const allowedOrigins = [ 'https://clone-chatgpt.firebaseapp.com', 'https://clone-chatgpt.web.app/' , 'http://localhost', 'http://127.0.0.1' ]
```
2. load the client.js code to https://clone-chatgpt.firebaseapp.com
Question where to load the server.js code ?

And the second question is what is the configuration of the redis base ?
